# Generated by Django 4.2.2 on 2023-10-16 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
                ('n_type', models.IntegerField(choices=[(0, 'Inmobiliario'), (1, 'Tecnología'), (2, 'Artículos de oficina'), (3, 'Otros')], default=3, verbose_name='Tipo de artefacto')),
                ('n_stock', models.PositiveIntegerField(default=0, verbose_name='Número de unidades en stock')),
            ],
            options={
                'verbose_name': 'Artefacto',
                'verbose_name_plural': 'Artefactos',
            },
            bases=('resources.resource',),
        ),
    ]
