# Generated by Django 4.2.2 on 2023-09-25 00:33

import apps.authuser.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('n_id', models.IntegerField(default=0)),
                ('t_id', models.IntegerField(choices=[(1, 'Cédula de ciudadanía'), (2, 'Tarjeta de identidad'), (3, 'Cédula de extranjería')], default=1)),
                ('n_phone', models.IntegerField(null=True)),
                ('t_rol', models.IntegerField(choices=[(0, 'Administrador Administrador'), (1, 'Administrador'), (2, 'Empleado'), (3, 'Cliente'), (4, 'Estudiante')], default=4)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuario',
            },
            managers=[
                ('objects', apps.authuser.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('n_points', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('apps.authuser.user',),
            managers=[
                ('objects', apps.authuser.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('n_salary', models.DecimalField(decimal_places=2, default=1000000, max_digits=10)),
                ('d_start_contract', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('d_end_contract', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empleados',
                'verbose_name_plural': 'Empleado',
            },
            bases=('apps.authuser.user',),
            managers=[
                ('objects', apps.authuser.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('n_points', models.IntegerField(blank=True, default=0)),
                ('n_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estudiantes',
                'verbose_name_plural': 'Estudiantes',
            },
            bases=('apps.authuser.user',),
            managers=[
                ('objects', apps.authuser.models.CustomUserManager()),
            ],
        ),
    ]
