# Generated by Django 4.2.2 on 2023-09-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
                ('n_type', models.IntegerField(choices=[(0, 'Salón de clase'), (1, 'Auditorio'), (2, 'Sala de informática'), (3, 'Sala de reuniones'), (4, 'Otros')], default=4, verbose_name='Tipo de lugar')),
                ('t_observation', models.CharField(max_length=255, verbose_name='Observaciones del lugar')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
            bases=('resources.resource',),
        ),
    ]
