# Generated by Django 4.2.2 on 2023-09-25 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Llave primaria artefacto')),
                ('t_name', models.CharField(max_length=255, verbose_name='Nombre del recurso')),
                ('d_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación del registro')),
                ('d_updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización del registro')),
                ('t_description', models.TextField(blank=True, null=True, verbose_name='Descripción del artefacto')),
                ('n_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio del artefacto')),
                ('b_status', models.IntegerField(choices=[(0, 'Activo'), (1, 'Inactivo'), (2, 'En reparación'), (3, 'Otros')], default=0, verbose_name='Estado del recurso')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
